customer.form.title=Customer Form
customer.form.shippinginfo=Shipping Info
customer.form.firstname=First Name
customer.form.lastname=Last Name
customer.form.address1=Address 1
customer.form.address2=Address 2
customer.form.country=Country
customer.form.state=State
customer.form.postalCode=Postal Code
customer.form.phoneNumber=Phone Number
customer.form.paymentinfo=Payment Information
customer.form.cardNumber=Card Number
customer.form.expMonth=Expiration Month
customer.form.expYear=Expiration Year
customer.form.securityCode=Security Code
customer.form.email=Email
customer.form.comments=Comments
customer.form.comments.remaining=Characters remaining: {0}
customer.form.submit=Submit
customer.form.scrollToTop=Scroll to Top
